config/routes.rb
Rails.application.routes.draw do
  match '*path', via: :all, to: 'errors#not_found',
      constraints: CloudfrontConstraint.new
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Skip routes for devise and specify custom controllers
  devise_for :users,
  controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" },
  path: '',
  skip: [:registrations, :sessions]

  # Add in custom routes for the ones previously skipped
  as :user do
    # Registration routes
    post 'users/:id' => 'users/registrations#create', as: :registration
    get 'register' => 'devise/registrations#new', as: :register

    # Session routes
    get 'sign-in' => 'users/sessions#new', as: :sign_in
    post 'sign-in' => 'users/sessions#create', as: :user_session
    delete 'sign_out' => 'users/sessions#destroy'

    # Forgot password
    get "forgot-password", to: "users/passwords#new", as: :forgot_password

    # Delete account
    delete "users/:id", to: "users#destroy"
  end

  get 'pdfs/no-invoice-found' => 'static_pages#no_invoice_found', as: :no_invoice_found

  get '/contact' => 'static_pages#contact', as: :contact
  post '/contact' => 'static_pages#send_contact', as: :send_contact

  # get '/about' => 'static_pages#about', as: :about

  get '/privacy_policy' => 'static_pages#privacy_policy', as: :privacy_policy

  root 'static_pages#home'

  patch '/invoices/:invoice_number' => 'invoices#update', as: :update_invoice
  resources :invoices, param: :invoice_number

  patch '/estimates/:estimate_number' => 'invoices#update', as: :update_estimate
  get '/estimates/new' => 'invoices#new', as: :new_estimate
  resources :estimates, param: :estimate_number, controller: 'invoices', except: [:new]

  # Email Invoice and Estimate
  post 'invoices/:invoice_number/send' => 'invoices#email_invoice', as: :send_email_invoice
  get 'invoices/:invoice_number/send' => 'invoices#email_invoice', as: :show_email_invoice

  post 'estimates/:estimate_number/send' => 'invoices#email_invoice', as: :send_email_estimate
  get 'estimates/:estimate_number/send' => 'invoices#email_invoice', as: :show_email_estimate

  # Public URL for PDF
  get '/pdfs/:token' => 'invoices#show', param: :token, :defaults => { :format => :pdf }, as: :public_invoice

  # User's profile and settings
  resources :users, only: [:update]
  get '/settings' => 'users#edit', as: :settings
  resources :settings, only: [:update]

  # Clients
  resources :clients, except: [:new, :show]

  # Logos
  resources :logos, only: [:create, :destroy]

  # Error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :redirect_if_logged_in, only: [:home]
	before_action :authenticate_user!, :except => [:home, :no_invoice_found, :contact, :send_contact, :about, :privacy_policy]

	def home
		@invoice = Invoice.new
		@invoice.jobs.build
	end

	def contact
		@email = ContactEmail.new
	end

	def send_contact
		if request.format.js?
			@email = ContactEmail.new(params[:contact_email])
			if @email.valid?

				if user_signed_in?
					@user = current_user
				else
					@user = nil
				end

				ContactMailer.contact_form(params[:contact_email][:name], params[:contact_email][:message], params[:contact_email][:email], @user).deliver_now
				flash[:success] = "Submission successful!"
				flash.keep(:success)
			end
		end

		respond_to do |format|
      		format.js
   	 	end
	end

	def about
	end

	def no_invoice_found
	end

	def privacy_policy
	end

	private
		def redirect_if_logged_in
			if user_signed_in?
				redirect_to invoices_url
			end
		end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_login_form.html.erb
<h3>Sign in to Simple Invoice</h3>
<div class="sessionerrortext">Invalid username or password.</div>
<%= form_for(:user, url: session_path(:user), remote: true, html: { class: "loginform" }) do |f| %>

    <%= f.label :email %>
    <%= f.email_field :email, id: "login_user_email", placeholder: "Email address" %>

    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>

    <%= link_to "Forgot Password", forgot_password_path, class: "forgotpassword" %>
    <%= f.submit "Log in", class: "button blue willload loginbutton" %>

    <div class="sessionbottomtext">Don't have an account? <%= link_to "Register", register_path, class: "showregister" %></div>

<% end %>

app/views/static_pages/_register_form.html.erb
<h3>Create a Simple Invoice Account</h3>
<p style="text-align:center">Registration is temporarily disabled</p>

app/views/static_pages/about.html.erb
<%= provide :title, "About" %>
<%= provide :special_class, " static" %>
<div id="pagewrapper" class="staticwrapper">

  <h1>About Simple Invoice</h1>
  <p>Simple Invoice is a passion project created by myself, <a href="http://www.christopherstiles.com">Chris Stiles.</a> I've worked as a freelance web designer for years. I'm always expanding my skillset and have found that building something yourself is the best way to learn.</p>
  <p>I started building Simple Invoice to help myself learn Ruby on Rails, a popular web application development framework. After taking several courses, I decided that the next step in my learning should be to jump in head first and develop an application from scratch.</p>
  <p>Invoicing clients to me was always a tedious, but necessary, practice. Manually creating PDFs for each client became a hassel to track. The different software programs I tried were—for the most part—expensive and offered more features than I needed.</p>
  <p>What I wanted was an application that just did the basics freelancers need, and did it well. This is why invoicing software was the perfect application for me to develop.</p>
  <p>I built this website from the ground up considering how I, as a freelancer, would like to invoice clients. The end result is a simple to use, powerful invoicing application you can access anywhere from any device.</p>
  <p>If you have any questions, bug reports, suggestions or feature requests, <%= link_to "please reach out", contact_path %>.</p>
  <p><br>I sincerely hope my hard work has paid off and you find Simple Invoice useful,<br><strong>Chris Stiles</strong></p>
</div>

app/views/static_pages/contact.html.erb
<%= provide :title, "Contact Us" %>
<%= provide :special_class, " static" %>
<div id="pagewrapper" class="staticwrapper smallbox paddinganimate registerbox nosidepadding">

  <h1>Contact Us</h1>

  <div id="validationerrors" class="clienterrors">
    <div class="validationtitle">
      <div class="closeerrors"></div>
      Please correct the following errors
      </div>
    <div id="errorholder"></div>
  </div>

<div class="formholder registerformholder">

  <div class="contactformholder">

      <div id="contactsuccess">
        <div id="contactsuccesscontent">
          Thank you for your submission. We will get back to you as soon as possible.
        </div>
      </div>

      <div id="contactform">
        <%= form_for(@email, url: send_contact_path, remote: true, html: { class: "registerform" }) do |f| %>

          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "Name" %>

          <%= f.label :email %>
          <%= f.email_field :email, placeholder: "Email address" %>

          <%= f.label :message %>
          <%= f.text_area :message, class: "modalinput contactmessage", placeholder: "Your message" %>

          <p class="staticsubmit"> <%= f.submit "Submit", class: "button blue willload registerbutton" %></p>

        <% end %>
      </div>

  </div>

</div>

</div>

app/views/static_pages/home.html.erb
<%= content_for(:nophone, true) %>
<%= content_for(:mobilesidebar, true) %>
<%= provide :title, "Free Online Invoice Generator" %>
<%= provide :special_class, " homepage nofixed static" %>


<div id="herotext">
	<h1>The simplest way for <br class="mobilebreak">freelancers to invoice their clients.</h1>
	<h2><span>Create and send invoices.</span><br class="mobilebreak"><span>Manage clients.</span> <span>Track payments.</span> <br class="mobilebreak freebreak"><span class="freespan">Completely free.</span></h2>
	<div id="dots"></div>
</div>

<div id="sessionoverlay">
	<div class="sessionclose"></div>
	<div class="sessionboxwrapper loginwrapper">
		<div class="sessionbox loginbox">
			<%= render 'login_form' %>
		</div>
	</div>
	<div class="sessionboxwrapper registerwrapper">
		<div class="sessionbox registerbox">
			<%= render 'register_form' %>
		</div>
	</div>
</div>


<div id="tryitout">
	<div class="trytext">Try it out!</div>
	<div class="successtext">Success!</div>
</div>

<div id="homeinvoicewrapper">
	<div id="homesuccesswrapper">
		<div id="homesuccesscontent">
			<h2>Invoice Created!</h2>
			<p>Click the button below to view your invoice.<br>
			This link will be remain active for 60 days. <%= link_to "Create an account", register_path, class: "showregister"%> now to save this invoice permanently and access other great features!</p>
			<a href="#" class="button blue viewinvoicebutton" target="_blank">View Invoice</a>
		</div>
	</div>


	<div id="formwrapper">
	<%= form_for(@invoice, remote: true) do |f| %>
	<%= hidden_field_tag :creating_from_root %>

	<div id="toolbar">
	  <div id="toolbarcontent">
	  	<div id="sociallinks">
			<div class="addthis_sharing_toolbox"></div>
		</div>
	    <%= f.submit 'Create Invoice', tabindex: '-1', class: "button blue willload saveicon" %>
	  </div>
	</div>

	<div id="mobilesidebarwrapper" class="invoicesidebar">
	  <aside id="sidebar">
	      <div class="scrollwrapper">
	      <div id="controls">
	        <h2>Date and Terms</h2>
	          <div class="control datecontrol">
	              <div class="alignment">
	                  <span>Date</span>
	                  <%= f.text_field :date, class: "datefield", readonly: true %>
	              </div>
	          </div>
	          <div class="control">
	              <div class="alignment">
	                  <span>Terms</span>
	                  <select class="terms">
	                    <option data-term="0">Same Day</option>
	                      <option data-term="7">7 Days</option>
	                      <option data-term="14">14 Days</option>
	                      <option data-term="21">21 Days</option>
	                      <option data-term="30" selected="selected">30 Days</option>
	                      <option data-term="45">45 Days</option>
	                      <option data-term="60">60 Days</option>
	                      <option data-term="90">90 Days</option>
	                      <option data-term="180">180 Days</option>
	                      <option data-term="365">365 Days</option>
	                  </select>
	              </div>
	          </div>
	          <div class="control duedatecontrol">
	              <div class="alignment">
	                  <span>Due</span>
	                  <%= f.text_field :due_date, class: "duedatefield", readonly: true %>
	              </div>
	          </div>
	          <h2>
	            Client
	          </h2>
	          <div class="control bonly">
	          <div class="alignment">
	              <span>Client Name</span>
	              <%= f.text_field :client_name, class: "clientnameinput", autocomplete: "off" %>
	              </div>
	          </div>

	      </div>
	      </div>
	  </aside>
	</div>

	<!-- Start Invioce -->

	<div id="mobilescrollwrapper">

	<div id="validationerrors">
	  <div class="validationtitle">
	    <div class="closeerrors"></div>
	    Please correct the following errors before saving
	  </div>
	  <div id="errorholder"></div>
	</div>

	<div id="invoicewrapper" class="new">

	    <div id="invoice">
	    
	      <section id="invoicenumber">
	                  <div>
	                  <%= f.text_field :invoice_number, value: "1" %>
	                  Invoice No. <span id="e-invoicenumber" class="onlynumber" <%= display_content_editable %>><%= @number %>1</span>
	            </div>
	       </section> 
	       
	      <section id="companyinformation">

	            <% unless no_current_logos? %>
	              <div id="invoicelogo">
	                  <%= f.hidden_field :logo, value: current_user.display_logo.url %>

	                  <%= f.hidden_field :logo_width, value: current_user.current_logo.logo_width, class: "logowidthfield" %>
	                  <%= f.hidden_field :logo_height, value: current_user.current_logo.logo_height, class: "logoheightfield" %>

	                  <div id="haslogo">
	                    <div id="logoresize">
	                      <%= image_tag current_user.display_logo.url, class: "invoicelogoimage", data: { width: current_user.current_logo.logo_width, height: current_user.current_logo.logo_height } %>
	                    </div>
	                  <div id="removelogobutton" class="removelogo">
	                    <span>Remove Logo</span>
	                  </div>
	                </div>
	                <div id="nologo">
	                  <div class="button blue addlogobutton" data-logo-url="<%= current_user.display_logo.url %>">Add Logo</div>
	                </div>
	              </div>
	            <% end %>

	            <div id="dateterms">
	                  <table border="0" cellspacing="0" cellpadding="0">
	                  <tbody>
	                    <tr>
	                      <td align="right">Date:</td>
	                      <td class="invoicesetting"><span id="e-date" <%= display_content_editable %>></span></td>
	                    </tr>
	                    <tr>
	                      <td align="right">Terms:</td>
	                      <td class="invoicesetting">
	                        <select class="terms">
	                            <option data-term="0">Same Day</option>
	                            <option data-term="7">7 Days</option>
	                            <option data-term="14">14 Days</option>
	                            <option data-term="21">21 Days</option>
	                            <option data-term="30" selected="selected">30 Days</option>
	                            <option data-term="45">45 Days</option>
	                            <option data-term="60">60 Days</option>
	                            <option data-term="90">90 Days</option>
	                            <option data-term="180">180 Days</option>
	                            <option data-term="365">365 Days</option>
	                        </select>
	                      </td>
	                    </tr>
	                    <tr>
	                      <td align="right">Due Date:</td>
	                      <td class="invoicesetting"><span id="e-duedate" <%= display_content_editable %>></span></td>
	                    </tr>
	                  </tbody>
	                </table>
	            </div>
	      </section>
	      
	       <section id="clientinformation">

	           <div id="userinfo">
	                  <%= f.text_field :name %>
	                  <span id="e-name" <%= display_content_editable %> placeholder="Name" name="invoice[name]"></span><br>
	                  <%= f.text_field :address_line1 %>
	                  <span id="e-address" <%= display_content_editable %> placeholder="Address" name="invoice[address_line1]"></span><br>
	                  <%= f.text_field :address_line2 %>
	                  <span id="e-cityzip" <%= display_content_editable %> placeholder="City, State, Zip" name="invoice[address_line2]"></span><br>
	                  <%= f.text_field :phone %>
	                  <span id="e-phone" <%= display_content_editable %> placeholder="Phone" name="invoice[phone]"></span>

	            </div>

	            <div id="clientinfo">
	                  <%= hidden_field_tag :client_id, @client_id %>
	                  <div class="sectiontitle">Bill To:</div>
	                  <span id="e-clientname" <%= display_content_editable %> placeholder="Client Name" name="invoice[client_name]"></span><br>
	                  <%= f.text_field :client_address_line1 %>
	                  <span id="e-clientaddress" <%= display_content_editable %> placeholder="Client Address" name="invoice[client_address_line1]"></span><br>
	                  <%= f.text_field :client_address_line2 %>
	                  <span id="e-clientcityzip" <%= display_content_editable %> placeholder="Client City, State, Zip" name="invoice[client_address_line2]"></span><br>
	            </div>
	       </section>
	       
	       <section id="invoiceitems">
	            <table width="100%" border="0" cellspacing="0" cellpadding="0">
	              <tbody>
	                      <tr class="tableheading">
	                        <th width="61%" align="left">Description</th>
	                        <th width="11%" align="right">Quantity</th>
	                        <th width="10%" align="right">Rate</th>
	                        <th width="18%" align="right">Amount</th>
	                      </tr>
	                      <%= f.fields_for :jobs do |c| %>
	                            <tr changed="false" class="jobrow">
	                              <td align="left" class="jobdescriptioncell">
	                                    <%= c.text_area :job_description, class: "job-description-box" %>
	                                    <span class="e-jobdescription job_description" <%= display_content_editable %> placeholder="Type a job description"></span>
	                              </td>
	                              <td align="right" class="quantitycell">
	                                    <%= c.text_field :job_quantity, class: "job-quantity-box"%>
	                                    <span class="e-quantity job_quantity" <%= display_content_editable %> placeholder="Quantity"></span>
	                              </td>
	                              <td align="right" class="ratecell">
	                                    <%= c.text_field :job_rate, class: "job-rate-box" %>
	                                    <span class="e-rate job_rate" <%= display_content_editable %> placeholder="Rate"></span>
	                              </td>
	                              <td align="right" class="amountcell">
	                                    <div class="amountbox"></div>
	                                    <div class="jobcontrols">
	                                    <div class="delete"></div>
	                                    <div class="insert"></div>
	                                </div>
	                              </td>
	                            </tr>
	                  <% end %>
	              </tbody>
	            </table>
	       </section>

	       <section id="invoicetax">
	          <div id="hastaxwrapper">
	            <div class="hastaxtitle">Tax: <span class="hastaxtext">No Tax</span></div>
	            <%= f.check_box :has_tax, class: "cmn-toggle cmn-toggle-round taxtoggle" %>
	            <%= f.label :has_tax, '', class: "cmn-toggle-1" %>
	          </div>
	          <div id="taxinformation">
	            <div class="taxamount">
	              <%= f.text_field :tax, class: "tax-rate-box onlynumber" %>
	              Tax: <span class="e-taxamount onlynumber" <%= display_content_editable %>></span> <span class="percentage">%</span>
	            </div>
	            <div class="taxincluded">
	              <div class="checkboxholder">
	                <%= f.check_box :tax_included, class: "includedtoggle" %>
	                <label for="invoice_tax_included"><span></span>
	                  <div>
	                    <div>Tax Inclusive:</div>
	                    <div class="inclusiontext">Not Included</div>
	                  </div>
	                </label>
	              </div>
	            </div>
	          </div>
	       </section>
	       
	       <section id="invoicetotal">
	            <div id="invoiceamount"></div>
	            <%= f.hidden_field :total, value: '0.00' %>
	            Total:
	       </section>
	       
	       <section id="notes">
	            <div class="sectiontitle notestitle">Notes:</div>
	            <%= f.text_area :notes %>
	            <div id="e-notes" <%= display_content_editable %> placeholder="Type any notes regarding the invoice here." name="invoice[notes]"></div>
	       </section>
	       
	    </div>
	</div>

	</div>
	<% end %>
	</div>

</div>

<div id="bottomsection">
	<div id="bottomsectioncontent">
		<p>Simple Invoice is a free online invoice generator. Create beautiful invoices online using your desktop, smartphone or tablet. </p>
		<p><%= link_to "Create a free account", register_path, class: "showregister" %> to save your invoices, add your logo, email your invoices, manage clients and track payments!</p>
	</div>
</div>


<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54ecd9630485c491"></script>

app/views/static_pages/no_invoice_found.html.erb
<%= provide :title, "No Invoice Found" %>
<%= provide :special_class, " static" %>
<div id="pagewrapper" class="staticwrapper smallbox">
	<h1>No Invoice Found</h1>
	<p>Are you sure your URL is correct? Invoices created by guests expire after 60 days.</p>
	<p><%= link_to "Create an account", register_path %> to save your invoices permanently!</p>
</div>

app/views/static_pages/privacy_policy.html.erb
<%= provide :title, "Privacy Policy" %>
<%= provide :special_class, " static" %>
<div id="pagewrapper" class="staticwrapper">
    <h1>Privacy Policy</h1>
    <p>This privacy policy discloses the privacy practices for https://www.simpleinvoice.io. This privacy policy applies solely to information collected by this web site. It will notify you of the following:</p>
    <ul>
        <li>What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.  </li>
        <li>What choices are available to you regarding the use of your data.  </li>
        <li>The security procedures in place to protect the misuse of your information.  </li>
        <li>How you can correct any inaccuracies in the information. </li>
    </ul>
    <p><strong>Information Collection, Use, and Sharing</strong> <br>
        We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.
    </p>
    <p>We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.</p>
    <p>Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</p>
    <p><strong>Your Access to and Control Over Information</strong> <br>
        You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:
    </p>
    <ul>
        <li>See what data we have about you, if any.</li>
        <li>Change/correct any data we have about you.</li>
        <li>Have us delete any data we have about you.</li>
        <li>Express any concern you have about our use of your data.</li>
    </ul>
    <p><strong>Security</strong> <br>
        We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.
    </p>
    <p>Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a closed lock icon in your web browser, or looking for "https" at the beginning of the address of the web page.</p>
    <p>While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p>
    <p><strong>Updates</strong><br>
        Our Privacy Policy may change from time to time and all updates will be posted on this page.
    </p>
    <p><strong>If you feel that we are not abiding by this privacy policy, you should contact us immediately at <a href="mailto:info@simpleinvoice.io">info@simpleinvoice.io</a>.</strong></p>
</div>

app/views/static_pages/send_contact.js.erb
var pageBody = $('body'),
	validationErrors = $('#validationerrors.clienterrors'),
	errorHolder = $('#errorholder');

setTimeout(function() {
	var oldContent = $('.buttoncontent').text();
	var button = $('.hasloadingtext');

	if (button.is('input')) {
		button.val(oldContent);
		button.prop('disabled', false);
	} else {
	button.text(oldContent);
	}

	button.removeClass('loading hasloadingtext');
	$('.buttoncontent').empty().remove();
	
}, 200);

<% if @email.errors.any? %>

errorHolder.empty();

<% @email.errors.each do |key, message| %>

var errorInput = $("*[name='contact_email[<%= key %>]']");
errorInput.addClass('haserror');

<% end %>

<% @email.errors.full_messages.each do |message| %>
	
	var message = '<%= message %>'
	errorHolder.append('<p>' + message + '</p>');

<% end %>

var errorHolderText = errorHolder.text();

if (errorHolderText.indexOf('Name') > -1 && errorHolderText.indexOf('Email') > -1) {
	var nameHTML = "";
	$('#validationerrors.clienterrors #errorholder p').each(function() {
		var $this = $(this);
		if ($this.text().indexOf('Name') > -1) {
			nameHTML += $this[0].outerHTML;
			$this.remove();
		}
	});
	errorHolder.prepend($(nameHTML));
} 

var validationsHeight = validationErrors.outerHeight(),
	negativeValidationsHeight = -1 * validationsHeight;

validationErrors.css({
	'margin-bottom' : negativeValidationsHeight,
	'display' : 'block'
});

//validationsHeight += 15;

$('.registerformholder').css({
  '-webkit-transform' : 'translate3d(0, ' + validationsHeight + 'px, 0)',
  '-moz-transform'    : 'translate3d(0, ' + validationsHeight + 'px, 0)',
  '-ms-transform'     : 'translate3d(0, ' + validationsHeight + 'px, 0)',
  '-o-transform'      : 'translate3d(0, ' + validationsHeight + 'px, 0)',
  'transform'         : 'translate3d(0, ' + validationsHeight + 'px, 0)'
});


var registerBox = $('.registerbox');
var registerBoxPadding = parseInt(registerBox.css('padding-bottom'));

registerBox.css({
	'padding-bottom' : validationsHeight + 50
});


<% else %>


pageBody.append('<div class="success"> <div class="successtimer"></div><div class="closesuccess"></div><span><%= flash[:success] %></span></div>');
<% flash.discard %>

$('.closeerrors').trigger('click');
var contactFormHolder = $('.contactformholder');
var newHeight = $('#contactsuccess').outerHeight() + 15;
contactFormHolder.addClass('emailsent');
contactFormHolder.animate({
	'height': newHeight,
	},
	{
	complete: function() {
		$('#contactform').remove();
	}
}, 300);



<% end %>