config/routes.rb
Rails.application.routes.draw do
  match '*path', via: :all, to: 'errors#not_found',
      constraints: CloudfrontConstraint.new
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Skip routes for devise and specify custom controllers
  devise_for :users,
  controllers: { sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords" },
  path: '',
  skip: [:registrations, :sessions]

  # Add in custom routes for the ones previously skipped
  as :user do
    # Registration routes
    post 'users/:id' => 'users/registrations#create', as: :registration
    get 'register' => 'devise/registrations#new', as: :register

    # Session routes
    get 'sign-in' => 'users/sessions#new', as: :sign_in
    post 'sign-in' => 'users/sessions#create', as: :user_session
    delete 'sign_out' => 'users/sessions#destroy'

    # Forgot password
    get "forgot-password", to: "users/passwords#new", as: :forgot_password

    # Delete account
    delete "users/:id", to: "users#destroy"
  end

  get 'pdfs/no-invoice-found' => 'static_pages#no_invoice_found', as: :no_invoice_found

  get '/contact' => 'static_pages#contact', as: :contact
  post '/contact' => 'static_pages#send_contact', as: :send_contact

  # get '/about' => 'static_pages#about', as: :about

  get '/privacy_policy' => 'static_pages#privacy_policy', as: :privacy_policy

  root 'static_pages#home'

  patch '/invoices/:invoice_number' => 'invoices#update', as: :update_invoice
  resources :invoices, param: :invoice_number

  patch '/estimates/:estimate_number' => 'invoices#update', as: :update_estimate
  get '/estimates/new' => 'invoices#new', as: :new_estimate
  resources :estimates, param: :estimate_number, controller: 'invoices', except: [:new]

  # Email Invoice and Estimate
  post 'invoices/:invoice_number/send' => 'invoices#email_invoice', as: :send_email_invoice
  get 'invoices/:invoice_number/send' => 'invoices#email_invoice', as: :show_email_invoice

  post 'estimates/:estimate_number/send' => 'invoices#email_invoice', as: :send_email_estimate
  get 'estimates/:estimate_number/send' => 'invoices#email_invoice', as: :show_email_estimate

  # Public URL for PDF
  get '/pdfs/:token' => 'invoices#show', param: :token, :defaults => { :format => :pdf }, as: :public_invoice

  # User's profile and settings
  resources :users, only: [:update]
  get '/settings' => 'users#edit', as: :settings
  resources :settings, only: [:update]

  # Clients
  resources :clients, except: [:new, :show]

  # Logos
  resources :logos, only: [:create, :destroy]

  # Error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/shared/_footer.html.erb
<footer <%= mobile_footer_class(is_mobile) %>>
	<div class="copy">
		&copy; <%= Time.now.year %>, Simple Invoice, All Rights Reserved <%= link_to "Privacy Policy", privacy_policy_path, class: "privacylink" %>
	</div>
	<div class="footernav">
		<%= link_to "Contact", contact_path %>
	</div>
</footer>

app/views/shared/_header.html.erb
<header>
	<%= link_to "", root_url, class: "logo" %>
	<div id="menu">
		<% if user_signed_in? %>
		<nav>
			<%= link_to "Invoices", invoices_path, class: "navinvoices#{current_page('invoices', 'invoice')}" %>
			<%= link_to "Estimates", estimates_path, class: "navestimates#{current_page('invoices', 'estimate')}" %>
			<%= link_to "Clients", clients_path, class: "navclients#{current_page('clients')}" %>
		</nav>

		<%= new_invoice_button("button blue newinvoiceicon") %>

		<div id="sessioninfo">
			<%= link_to "Log Out", sign_out_path, :method => :delete, class: "navsignout" %>
			<%= link_to "Settings", settings_path, class: "navprofile#{current_page('users')}" %>
		</div>

		<% else %>
			<div id="sessioninfo" class="notsignedin">
				<%= link_to "Register", register_path, class: "showregister#{current_page('registrations')}" %>
				<%= link_to "Sign In", sign_in_path, class: "signinbutton#{current_page('sessions')}" %>
				<%= link_to "Home", root_url, class: "sessionhome" %>
			</div>
		<% end %>	
	</div>	
</header>

app/views/shared/_meta_tags.html.erb
 <%= favicon_link_tag 'favicon.png' %>
<meta name="description" content="Simple Invoice is a free online invoice generator. The simplest way for freelancers to invoice their clients">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta property="fb:app_id" content="627013050809394"/>
<meta property="og:site_name" content="Simple Invoice" />
<meta property="og:url" content="https://www.simpleinvoice.io" />
<meta property="og:title" content="Simple Invoice" />
<meta property="og:description" content="The simplest way for freelancers to invoice their clients." />
<meta property="og:image" content="http://s3-us-west-1.amazonaws.com/invoiceapplication/public/invoicer-facebook.png" />
<meta property="og:image:secure_url" content="https://s3-us-west-1.amazonaws.com/invoiceapplication/public/invoicer-facebook.png" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@Simple_Invoice">
<meta name="twitter:creator" content="@Simple_invoice">
<meta name="twitter:title" content="Simple Invoice">
<meta name="twitter:description" content="The simplest way for freelancers to invoice their clients.">
<meta name="twitter:image" content="https://s3-us-west-1.amazonaws.com/invoiceapplication/public/invoicer-facebook.png">
<%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>